apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-success
  name: nginx-success
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-success
  template:
    metadata:
      labels:
        app: nginx-success
    spec:
      containers:
      - image: nginx
        name: nginx-success
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
